name: test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install --legacy-peer-deps

      - name: Jest
        run: npm run jest

      - name: Cypress Component Tests
        run: npm run cy:comp
